// Versioned legal content. Bump LEGAL_VERSION when any policy materially changes.
export const LEGAL_VERSION = "2026-06-20";
export const LAST_UPDATED = "June 20, 2026";

export const ABUSE_EMAIL = "abuse@xellvio.com";
export const PRIVACY_EMAIL = "privacy@xellvio.com";
export const SUPPORT_EMAIL = "support@xellvio.com";
export const LEGAL_ENTITY = "Xellvio";

function fill(md: string) {
  return md
    .replace(/\[DATE\]/g, LAST_UPDATED)
    .replace(/\[LEGAL ENTITY NAME\]/g, LEGAL_ENTITY)
    .replace(/\[BUSINESS ADDRESS\]/g, "Address available on request")
    .replace(/\[PRIVACY EMAIL[^\]]*\]/g, PRIVACY_EMAIL)
    .replace(/\[ABUSE EMAIL[^\]]*\]/g, ABUSE_EMAIL)
    .replace(/\[SUPPORT EMAIL\]/g, SUPPORT_EMAIL)
    .replace(/\[SUPPORT\/LEGAL EMAIL\]/g, SUPPORT_EMAIL)
    .replace(/\[JURISDICTION\]/g, "the Federal Republic of Nigeria")
    .replace(/\[THREE \(3\)\]/g, "three (3)");
}

export type LegalDoc = {
  slug: string;
  path: string;
  title: string;
  short: string;
  description: string;
  markdown: string;
  toc: boolean;
};

export const PRIVACY_MD = fill(`# Privacy Policy

**Last updated: [DATE]**

This Privacy Policy explains how Xellvio ("Xellvio," "we," "us," or "our") collects, uses, shares, and protects personal information in connection with the Xellvio platform and the website at https://xellvio.com (together, the "Service"). It also describes the rights and choices available to you.

Xellvio is operated by [LEGAL ENTITY NAME], [BUSINESS ADDRESS] ("we"). For privacy questions or to exercise your rights, contact us at [PRIVACY EMAIL].

---

## 1. Our Two Roles: Controller and Processor

Xellvio plays two different roles depending on whose data is involved:

- **As a controller** — for personal information about our Customers (the businesses and individuals who sign up) and website visitors, we decide how and why the data is processed. This policy governs that processing.
- **As a processor** — when our Customers upload contact lists and send campaigns, the personal information of their recipients ("End User Data") is controlled by the Customer. We process it only on the Customer's documented instructions to provide the Service, as described in our Data Processing Addendum. End Users with questions about a specific message should contact the business that sent it.

## 2. Information We Collect

**Account and business information** — name, business name, email, phone number, business address, business registration details, role, and login credentials.

**Billing information** — billing contact, transaction history, and payment details (processed by our payment provider; we do not store full card numbers).

**Customer content and End User Data** — contact phone numbers and names, consent records, message content, campaign configurations, segments, and delivery and engagement data, all uploaded or generated by Customers.

**Usage and device data** — IP address, browser and device type, operating system, log files, timestamps, pages and features used, and referring URLs.

**Communications** — messages you send to our support team and related metadata.

**Cookies and similar technologies** — see our Cookie Policy.

### What we collect, why, and our legal basis

| Category | Examples | Purpose | Legal basis (where GDPR/UK GDPR applies) |
|---|---|---|---|
| Account data | Name, email, business details | Create and manage accounts; authenticate | Contract; legitimate interests |
| Billing data | Billing contact, transactions | Process payments; manage credits | Contract; legal obligation |
| Customer content | Contacts, messages, campaigns | Deliver the Service | Contract (and, for End User Data, our role as processor) |
| Usage/device data | IP, logs, feature usage | Operate, secure, and improve the Service | Legitimate interests |
| Compliance data | Verification, identity, consent records | Meet legal and carrier requirements; prevent abuse | Legal obligation; legitimate interests |

## 3. How We Use Information

We use personal information to operate, maintain, and secure the Service; create and authenticate accounts; deliver messages on Customers' behalf; process payments and manage credit balances; provide support; detect, investigate, and prevent fraud, abuse, and violations of our Acceptable Use and Anti-Spam policies; comply with legal, regulatory, and carrier obligations (including messaging registration and verification); and analyze and improve the Service.

## 4. Mobile Information and Text Messaging — Important Disclosure

**No mobile information (including phone numbers and SMS opt-in or consent data) will be shared with or sold to third parties or affiliates for marketing or promotional purposes.** All categories of data sharing described in this policy exclude text-messaging originator opt-in data and consent; this information will not be shared with any third parties for their own marketing purposes.

Mobile and consent information is used only to deliver the messaging requested by you or by the Customer whose list you joined, and to meet telecommunications-compliance obligations.

## 5. How We Share Information

We share personal information only as described here:

- **Subprocessors and service providers** — including our messaging infrastructure provider (Telnyx), cloud hosting and database provider, payment processor, email and analytics providers. They act on our instructions under contract. A current list is maintained in our Subprocessor List. Delivering a message necessarily transmits the recipient's number and message content to telecommunications carriers.
- **Legal, safety, and compliance** — where required by law, regulation, legal process, carrier rules, or to protect the rights, property, or safety of Xellvio, our Customers, End Users, or the public, and to enforce our terms.
- **Business transfers** — in connection with a merger, acquisition, financing, or sale of assets, subject to this policy.

We do not sell personal information, and we do not share mobile opt-in or consent data for third-party marketing.

## 6. Data Retention

We retain personal information for as long as an account is active and as needed to provide the Service, then only as long as necessary to comply with legal obligations, resolve disputes, maintain security, and enforce our agreements. Customers may request deletion as described in Section 8 and in our Data Processing Addendum.

## 7. Data Security

We maintain administrative, technical, and organizational safeguards designed to protect personal information, including encryption of sensitive credentials, access controls, and tenant isolation. No system is perfectly secure, and we cannot guarantee absolute security.

## 8. Your Rights and Choices

Depending on your location, you may have the right to access, correct, delete, or port your personal information; to restrict or object to processing; and to withdraw consent. To exercise these rights, contact [PRIVACY EMAIL]; we may need to verify your identity. End Users should direct requests to the Customer who controls their data, and we will support that Customer in responding.

**Opt out of messages at any time** by replying STOP to any message; reply HELP for assistance.

### Region-specific rights

**EEA / United Kingdom (GDPR / UK GDPR).** You have the rights listed above and the right to lodge a complaint with your supervisory authority. Where we rely on legitimate interests, you may object. International transfers are protected by appropriate safeguards such as Standard Contractual Clauses.

**California (CCPA / CPRA).** You have the right to know, access, correct, and delete personal information, and to opt out of "sale" or "sharing" — we do not sell or share personal information as those terms are defined. We will not discriminate against you for exercising your rights.

**Nigeria (NDPR) and other regions.** Where local data-protection laws apply, we honor the rights and obligations they provide. Contact us for region-specific requests.

## 9. International Data Transfers

We and our subprocessors may process personal information in countries other than yours. Where required, we apply appropriate safeguards (such as Standard Contractual Clauses) for cross-border transfers.

## 10. Children's Privacy

The Service is intended for businesses and is not directed to individuals under 18 (or the age of majority where they live). We do not knowingly collect their personal information.

## 11. Cookies

We use cookies and similar technologies to run the Service, maintain sessions, remember preferences, and analyze usage. See our Cookie Policy for details and choices.

## 12. Changes to This Policy

We may update this Privacy Policy from time to time. We will post the revised version with a new "Last updated" date and, where appropriate, provide additional notice of material changes.

## 13. Contact Us

[LEGAL ENTITY NAME]
[BUSINESS ADDRESS]
Email: [PRIVACY EMAIL]
`);

export const TERMS_MD = fill(`# Terms of Service

**Last updated: [DATE]**

These Terms of Service ("Terms") form a binding agreement between you ("Customer," "you") and [LEGAL ENTITY NAME] ("Xellvio," "we," "us," or "our") and govern your access to and use of the Xellvio platform and website at https://xellvio.com (the "Service"). By creating an account, clicking to accept, or using the Service, you agree to these Terms. If you are agreeing on behalf of an organization, you represent that you are authorized to bind it.

---

## 1. Definitions

- **"Customer Data"** means data, content, and contact information you upload or generate through the Service, including End User personal information.
- **"End User"** means a person who receives messages you send through the Service.
- **"Credits"** means the prepaid balance used to pay for messages and fees.
- **"Documentation"** means our published guides and policies, including the Acceptable Use Policy, Anti-Spam & Messaging Policy, Privacy Policy, and Data Processing Addendum, each incorporated into these Terms.

## 2. The Service

Xellvio provides a platform to create accounts, provision messaging senders, manage contacts and consent, and send SMS and other messaging campaigns. Messages are delivered through third-party telecommunications infrastructure. We may add, change, or remove features over time.

## 3. Eligibility and Accounts

You must be at least 18 and able to enter a binding contract. You must provide accurate business and identity information and keep it current, and you must complete any identity, business, or messaging verification we or carriers require before sending. You are responsible for all activity under your account and for safeguarding credentials. Notify us promptly of any unauthorized use.

## 4. Acceptable Use and Messaging Compliance

Your use is governed by our Acceptable Use Policy and Anti-Spam & Messaging Policy. You are solely responsible for your messages and for obtaining and documenting valid consent from every recipient. You represent and warrant that, for each message:

- You have obtained valid, prior express consent in compliance with all applicable laws (including the TCPA, CAN-SPAM, CASL, GDPR, PECR, and local equivalents) and carrier rules;
- You will honor opt-out (STOP) and help (HELP) requests;
- You will include required disclosures and identify yourself as the sender;
- Your registration and verification information is accurate.

You acknowledge that messaging registration and verification (including toll-free verification and A2P/10DLC registration) are performed by carriers and third parties, that approval is not guaranteed, and that sending may be delayed, throttled, or blocked pending approval or for compliance reasons.

## 5. Fees, Credits, and Payment

The Service uses a prepaid Credit model. You purchase Credits in advance; message sends and applicable fees are deducted based on destination country, number type, and message segments. Per-message pricing is set out in the Service and may change on a going-forward basis. **Credits are non-refundable except where required by law, do not constitute a deposit or stored monetary value, and may expire if your account is inactive or closed.** You are responsible for all applicable taxes other than taxes on our income. We may suspend sending if your balance is insufficient.

## 6. Customer Data and Data Protection

As between the parties, you retain all rights in Customer Data. You grant us a limited, worldwide license to host, process, and transmit Customer Data solely to provide and support the Service. You are the controller of Customer Data and are responsible for its lawful collection and use; we act as your processor under our Data Processing Addendum, which is incorporated into these Terms. Our handling of personal information is described in our Privacy Policy.

## 7. Suspension and Termination

We may suspend or terminate your account or any sender, immediately and without liability, if we reasonably believe you have violated these Terms or the Documentation; if required by a carrier, regulator, or law; if your activity threatens the security, integrity, or reputation of the Service or others; or for non-payment. Where practical we will give notice, but for compliance or security risks we may act first. You may close your account at any time. Sections that by their nature should survive (including Sections 5, 6, 9–12, and 14) survive termination.

## 8. Service Availability and Support

We strive to keep the Service available but do not warrant uninterrupted or error-free operation, and we may perform maintenance or modify the Service. Message delivery depends on third-party carriers and is not guaranteed. Support is provided as described on our website.

## 9. Third-Party Services

The Service relies on third-party providers (including messaging infrastructure and payment processors). We are not responsible for the acts, omissions, pricing changes, or availability of third-party carriers, though we will use commercially reasonable efforts to maintain integrations.

## 10. Disclaimers

THE SERVICE AND DOCUMENTATION ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY LAW.

## 11. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, XELLVIO AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, REVENUES, OR DATA. OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNTS YOU PAID US IN THE [THREE (3)] MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM.

## 12. Indemnification

You will defend, indemnify, and hold harmless Xellvio and its affiliates, officers, and employees from any third-party claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising out of or relating to your Customer Data, your messages, your use of the Service, your violation of these Terms or the Documentation, or your violation of any law or third-party right — including any claim arising from your failure to obtain proper consent.

## 13. Changes to These Terms

We may update these Terms from time to time by posting the revised version with a new "Last updated" date. Material changes may receive additional notice. Continued use after changes take effect constitutes acceptance.

## 14. Governing Law and Disputes

These Terms are governed by the laws of [JURISDICTION], without regard to conflict-of-laws principles. The parties submit to the exclusive jurisdiction of the courts located in [JURISDICTION], except where applicable law provides otherwise.

## 15. General

These Terms, together with the incorporated Documentation, are the entire agreement between the parties regarding the Service. If any provision is unenforceable, the rest remains in effect. Our failure to enforce a provision is not a waiver. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets.

## 16. Contact

[LEGAL ENTITY NAME]
[BUSINESS ADDRESS]
Email: [SUPPORT/LEGAL EMAIL]
`);

export const AUP_MD = fill(`# Acceptable Use Policy

**Last updated: [DATE]**

This Acceptable Use Policy ("AUP") governs use of the Xellvio platform (the "Service") and is incorporated into our Terms of Service. It works alongside our Anti-Spam & Messaging Policy. The AUP protects recipients, carriers, and the integrity of the Service. Violations may result in immediate suspension or termination, content removal, and reporting to carriers, regulators, or law enforcement.

You are responsible for ensuring that you, your team, and anyone using your account comply with this AUP.

---

## 1. Consent Is Mandatory

You may only message recipients who have given valid, documented, prior express consent. You must:

- Keep records of consent (when, how, and exactly what the recipient agreed to);
- Send only the categories of messages the recipient agreed to receive;
- Present clear consent disclosures at opt-in (your identity, message purpose and frequency, "message and data rates may apply," links to your Privacy Policy and Terms, and how to opt out and get help);
- Never message purchased, rented, scraped, appended, or otherwise non-consented contacts.

## 2. Honor Opt-Outs and Help Requests

You must honor STOP, UNSUBSCRIBE, and equivalent requests immediately, and respond to HELP requests. You must not message a person who has opted out unless they re-subscribe, and you must not disable, circumvent, or interfere with opt-out handling.

## 3. Prohibited and Restricted Content

You may not use the Service to send, promote, or facilitate messages relating to:

- Illegal goods, services, or activities of any kind;
- Fraud, scams, phishing, deceptive or misleading marketing, fake offers, or impersonation of any person or brand;
- "S.H.A.F.T." content where restricted by carriers or law — Sex (including adult or sexually explicit content), Hate (hate speech, harassment, threats, content promoting violence or discrimination), Alcohol, Firearms (and weapons, ammunition, fireworks), and Tobacco/vaping;
- Cannabis, CBD, kratom, and illegal or controlled substances;
- Prescription medication offered without a valid prescription, and illegitimate pharmaceutical sales;
- Gambling, sweepstakes, lotteries, and contests where restricted;
- High-risk financial services — payday, short-term, and high-interest loans; debt collection, consolidation, reduction, or credit-repair; deceptive investment, cryptocurrency, or "get rich quick" schemes;
- Multi-level marketing, pyramid schemes, and deceptive "work from home" offers;
- Lead generation that shares or sells phone numbers or consent without proper authorization;
- Malware, spyware, viruses, or other harmful code, and links to such content.

We may add to or refine restricted categories to reflect carrier and legal requirements.

## 4. Prohibited Practices

You may not:

- Send spam, bulk unsolicited messages, or messages to non-consented recipients;
- Misrepresent your identity, business, or the origin, purpose, or content of your messages;
- Evade, manipulate, or circumvent carrier filtering, registration, throughput limits, or compliance controls — including "snowshoeing" traffic across numbers, URL cloaking, public URL shorteners used to disguise destinations, or using multiple senders or accounts to bypass limits or a suspension;
- Provide false or misleading information during sender registration or verification;
- Harvest, sell, or share recipient data in violation of law or our Privacy Policy;
- Interfere with, overburden, or disrupt the Service or other users, or attempt unauthorized access to any system;
- Use the Service for unsolicited automated, abusive, or excessive traffic;
- Resell or provide third-party access to the Service in violation of this AUP or carrier rules without authorization.

## 5. Legal and Regulatory Compliance

You are solely responsible for complying with all applicable laws and regulations in every jurisdiction you send to, including the TCPA, CAN-SPAM Act, CASL, GDPR, PECR, applicable telecommunications and consumer-protection laws, and all carrier requirements and registration obligations.

## 6. Accurate Registration

All information you submit for sender provisioning and verification — business details, use case, sample messages, opt-in description, volumes — must be accurate and truthful. False information may result in termination and may itself violate carrier rules and law.

## 7. Monitoring and Enforcement

We may monitor use of the Service to assess compliance and investigate suspected violations. At our sole discretion and, where compliance or security requires, without prior notice, we may suspend or terminate accounts, block or remove campaigns or content, halt sending immediately, and report violations to carriers, regulators, or law enforcement. We are not obligated to monitor, and not enforcing a provision is not a waiver of our right to do so later.

## 8. Reporting Abuse

Report suspected abuse or AUP violations to [ABUSE EMAIL].

## 9. Changes

We may update this AUP at any time by posting a revised version. Continued use after changes take effect constitutes acceptance.
`);

export const ANTI_SPAM_MD = fill(`# Anti-Spam & Messaging Compliance Policy

**Last updated: [DATE]**

Xellvio (https://xellvio.com) is committed to keeping messaging trusted, wanted, and compliant. This Anti-Spam & Messaging Compliance Policy sets the standards every Customer must meet to send through the Service. It supplements our Terms of Service and Acceptable Use Policy. Failure to comply may result in immediate suspension or termination and reporting to carriers and authorities.

---

## 1. Consent Is the Foundation

Every message you send must be based on valid, prior express consent from the recipient. "Consent" means the recipient knowingly and affirmatively agreed to receive the specific type of messages you are sending, from your specific business.

Acceptable proof of consent includes a record of:

- **When** consent was given (timestamp);
- **How** it was given (web form, checkbox, keyword opt-in, point of sale, etc.);
- **What** the recipient agreed to (the disclosure text shown at opt-in);
- The **phone number** that consented.

Consent must not be bundled deceptively, pre-checked, or buried. Consent to marketing messages may not be a condition of purchase.

## 2. Prohibited Sources of Contacts

You may **not** send to numbers obtained from: purchased, rented, traded, or leased lists; scraped or harvested sources; third-party "appended" data; or any list where you cannot demonstrate direct consent given to *your* business. Sending to such lists is the most common cause of spam complaints and account termination.

## 3. Required Elements in Every Program

Your messaging program must include:

- **Sender identification** — recipients must know which business is messaging them;
- **Opt-out on demand** — STOP and equivalents honored immediately and automatically;
- **Help on demand** — a HELP response with contact information;
- **Accurate content** — no misleading sender info, subject matter, or links;
- **Required disclosures at opt-in** — purpose, frequency, "message and data rates may apply," and links to your Privacy Policy and Terms.

## 4. Prohibited Sending Practices

The following are strictly prohibited:

- Unsolicited messages ("spam") of any kind;
- Messaging recipients who have opted out;
- Disguising, hiding, or falsifying the origin or routing of messages;
- Evading carrier filters, registration, or throughput limits — including spreading traffic across many numbers to avoid detection ("snowshoeing"), rotating senders to dodge complaints, or using multiple accounts to bypass a suspension;
- Public/free URL shorteners or link cloaking that hide a message's true destination;
- Sending prohibited or restricted content as defined in the Acceptable Use Policy;
- Manipulating engagement metrics or consent records.

## 5. Registration and Verification Integrity

Messaging to many destinations requires sender registration and verification (for example, toll-free verification and A2P/10DLC brand and campaign registration). You must provide truthful, accurate information for these processes, including your real business identity, genuine use case, real sample messages, and an accurate description of how you collect consent. Misrepresentation may result in termination and may violate carrier rules and law.

## 6. Complaint and Quality Monitoring

We and carriers monitor signals such as spam complaints, opt-out rates, unknown-number rates, and content flags. Sustained poor metrics or complaint spikes may trigger throttling, review, suspension, or termination, regardless of whether an explicit rule was broken. Maintaining list hygiene and sending only wanted messages is your responsibility.

## 7. Enforcement

We may, at our discretion and where necessary without prior notice, investigate, throttle, suspend, or terminate accounts; block content or campaigns; halt sending; and report violations to carriers, regulators, or law enforcement. We may act immediately where compliance, security, or carrier obligations require it.

## 8. Reporting

To report spam or a violation of this policy, contact [ABUSE EMAIL].

## 9. Changes

We may update this policy at any time by posting a revised version. Continued use after changes take effect constitutes acceptance.
`);

export const SMS_TERMS_MD = fill(`# SMS / Messaging Terms & Consent

**Last updated: [DATE]**

These SMS/Messaging Terms describe how text messaging works on the Xellvio platform (https://xellvio.com), the consent practices that apply, and the disclosures required by carriers and applicable law. They are written for both End Users who receive messages and Customers who send them.

---

## For End Users (people receiving messages)

**Consent.** When you provide your mobile number and opt in — by submitting a sign-up form, checking a consent box, or texting a keyword to a business that uses Xellvio — you agree to receive text messages from that business at the number you provided. Consent to receive marketing messages is not a condition of any purchase.

**Program and sender.** Messages are sent by the business you subscribed to, using messaging infrastructure provided through Xellvio.

**Message frequency.** Frequency varies depending on the business and program you joined.

**Costs.** Message and data rates may apply, depending on your mobile carrier and plan.

**Opt out.** You can cancel at any time by replying **STOP** to any message. You will receive one confirmation and then no further messages from that program unless you re-subscribe.

**Help.** Reply **HELP** for assistance, or contact the business that messaged you. You can also reach us at [SUPPORT EMAIL].

**Carriers.** Wireless carriers are not liable for delayed or undelivered messages.

**Privacy.** Your mobile information and opt-in/consent data are never shared with or sold to third parties or affiliates for marketing purposes. See our Privacy Policy.

---

## For Customers (businesses sending messages)

By sending through Xellvio you agree, in addition to our Terms of Service, Acceptable Use Policy, and Anti-Spam & Messaging Policy, that:

1. **You obtain and document valid consent.** You will only message recipients who gave prior express consent in compliance with the TCPA, CAN-SPAM, CASL, GDPR, PECR, and all applicable laws and carrier rules, and you will retain proof.

2. **Your opt-in includes the required disclosures.** Your sign-up flow must clearly state: your business identity; the type and purpose of messages; expected frequency; "message and data rates may apply"; links to your Privacy Policy and Terms; and opt-out (Reply STOP) and help (Reply HELP) instructions.

3. **You honor STOP, HELP, and START.** These are processed automatically by the platform; you must not circumvent them.

4. **You send only permitted content** consistent with our Acceptable Use Policy, avoiding prohibited and restricted categories.

5. **Your registration and verification information is accurate** — including your business profile, use case, sample messages, and opt-in description used for toll-free verification and A2P/10DLC registration.

6. **You are responsible for your messages** — their content, targeting, legality, and the consent behind them.

## Sample Consent Language (adapt for your sign-up forms)

> "By providing your phone number and checking this box, you agree to receive recurring automated marketing and informational text messages from [Your Business] at the number provided. Consent is not a condition of purchase. Message frequency varies. Message and data rates may apply. Reply STOP to unsubscribe or HELP for help. See our Privacy Policy [link] and Terms [link]."

## Sample Keyword Responses

- **STOP:** "[Your Business]: You are unsubscribed and will receive no more messages. Reply START to re-subscribe."
- **HELP:** "[Your Business]: For help, contact [email/phone]. Msg & data rates may apply. Reply STOP to unsubscribe."
- **START / confirmation:** "[Your Business]: You're subscribed. Msg frequency varies. Msg & data rates may apply. Reply HELP for help, STOP to cancel."

## Contact

[LEGAL ENTITY NAME]
Email: [SUPPORT EMAIL]
Website: https://xellvio.com
`);

export const DPA_MD = fill(`# Data Processing Addendum (DPA)

**Last updated: [DATE]**

This Data Processing Addendum ("DPA") forms part of the Terms of Service between [LEGAL ENTITY NAME] ("Xellvio," "Processor") and the Customer ("Controller") and applies to Xellvio's processing of personal data on the Customer's behalf in connection with the Xellvio platform (https://xellvio.com, the "Service"). Where the Customer's End User contact data is processed, the Customer is the controller and Xellvio is the processor.

---

## 1. Definitions

Terms such as "personal data," "processing," "controller," "processor," "data subject," and "supervisory authority" have the meanings given under applicable data-protection law (including the GDPR and UK GDPR). "Applicable Data Protection Law" means all privacy and data-protection laws applicable to the processing.

## 2. Roles and Scope

The Customer is the controller and Xellvio is the processor of Customer Data containing personal data. Xellvio processes such personal data only to provide and support the Service and on the Customer's documented instructions, including as set out in the Terms and this DPA. Xellvio will inform the Customer if, in its opinion, an instruction infringes Applicable Data Protection Law.

## 3. Customer Obligations

The Customer warrants that it has a valid legal basis and all necessary consents for the personal data it uploads and the messages it sends, that its instructions comply with Applicable Data Protection Law, and that it has provided required notices to data subjects.

## 4. Xellvio Obligations

Xellvio will: (a) process personal data only on documented instructions; (b) ensure persons authorized to process are bound by confidentiality; (c) implement appropriate technical and organizational security measures (Annex B); (d) assist the Controller, taking into account the nature of processing, with data-subject requests and with security, breach-notification, and impact-assessment obligations; and (e) make available information reasonably necessary to demonstrate compliance.

## 5. Subprocessors

The Customer authorizes Xellvio to engage subprocessors to provide the Service. Current subprocessors are listed in our Subprocessor List. Xellvio imposes data-protection obligations on each subprocessor substantially similar to those in this DPA and remains responsible for their performance. Xellvio will give notice of intended changes to subprocessors, and the Customer may object on reasonable data-protection grounds.

## 6. Data Subject Requests

Taking into account the nature of the processing, Xellvio will assist the Controller by appropriate measures, insofar as possible, to respond to data subjects exercising their rights. If Xellvio receives a request directly from a data subject, it will, where permitted, direct them to the Controller.

## 7. Personal Data Breach

Xellvio will notify the Controller without undue delay after becoming aware of a personal data breach affecting Customer Data, and will provide information reasonably available to assist the Controller in meeting its notification obligations.

## 8. International Transfers

Where processing involves transfer of personal data across borders, the parties will rely on an appropriate transfer mechanism under Applicable Data Protection Law, such as the Standard Contractual Clauses, which are incorporated by reference where applicable.

## 9. Deletion and Return

Upon termination of the Service, Xellvio will, at the Controller's choice, delete or return Customer Data containing personal data, except where retention is required by law, within a commercially reasonable period.

## 10. Audit

Xellvio will make available information necessary to demonstrate compliance with this DPA and will allow for and contribute to audits, including inspections, conducted by the Controller or an auditor it mandates, subject to reasonable confidentiality and security conditions and reasonable notice.

## 11. Liability

Each party's liability under this DPA is subject to the limitations and exclusions of liability set out in the Terms of Service.

---

## Annex A — Details of Processing

- **Subject matter:** provision of the Xellvio messaging platform.
- **Duration:** the term of the Customer's account.
- **Nature and purpose:** hosting, storing, transmitting, and delivering messages and managing contacts and consent on the Controller's behalf.
- **Categories of data subjects:** the Customer's contacts and message recipients (End Users); the Customer's authorized users.
- **Categories of personal data:** names, mobile phone numbers, consent records, message content, and engagement/delivery data.
- **Special categories:** none intended; the Customer must not upload special-category data without a lawful basis and appropriate safeguards.

## Annex B — Security Measures

Xellvio maintains measures including: encryption of sensitive credentials in transit and at rest; access controls and least-privilege permissions; tenant isolation through row-level security; secrets management; logging and monitoring; secure software-development practices; and incident-response procedures.

## Annex C — Subprocessors

See the current Subprocessor List, including (by way of example) the messaging infrastructure provider (Twilio), cloud hosting and database provider, and payment processor.

---

## Contact

[LEGAL ENTITY NAME] — [PRIVACY EMAIL]
`);

export const COOKIES_MD = fill(`# Cookie Policy

**Last updated: [DATE]**

This Cookie Policy explains how Xellvio ("we," "us," "our") uses cookies and similar technologies on the website and platform at https://xellvio.com (the "Service"). It supplements our Privacy Policy.

---

## 1. What Cookies Are

Cookies are small text files placed on your device when you visit a website. We also use similar technologies such as local storage, pixels, and tags. Together these help the Service function, remember your preferences, and understand how the Service is used.

## 2. Types of Cookies We Use

**Strictly necessary** — required to operate the Service, keep you signed in, maintain sessions, and protect security. The Service cannot function properly without these.

**Functional** — remember your preferences and settings to improve your experience.

**Analytics / performance** — help us understand how the Service is used so we can improve it. These collect information such as pages visited and features used, often in aggregated or pseudonymized form.

**We do not use cookies to share your mobile opt-in or SMS consent data with third parties for their marketing purposes.**

## 3. Third-Party Cookies

Some cookies may be set by our service providers (for example, analytics or payment providers) to perform services on our behalf. Their use of information is governed by their own policies.

## 4. Your Choices

You can control or delete cookies through your browser settings, and you can usually set your browser to refuse cookies or alert you when they are set. If you disable strictly necessary cookies, parts of the Service may not work. Where required by law, we will request your consent for non-essential cookies through a cookie banner or preference tool.

## 5. Changes

We may update this Cookie Policy from time to time by posting a revised version with a new "Last updated" date.

## 6. Contact

[LEGAL ENTITY NAME]
Email: [PRIVACY EMAIL]
`);

export const LEGAL_DOCS: Record<string, LegalDoc> = {
  privacy: { slug: "privacy", path: "/privacy", title: "Privacy Policy", short: "Privacy", description: "How Xellvio collects, uses, and protects personal information.", markdown: PRIVACY_MD, toc: true },
  terms: { slug: "terms", path: "/terms", title: "Terms of Service", short: "Terms", description: "The binding terms that govern use of the Xellvio platform.", markdown: TERMS_MD, toc: true },
  aup: { slug: "aup", path: "/aup", title: "Acceptable Use Policy", short: "Acceptable Use", description: "Rules every Xellvio customer must follow when using the platform.", markdown: AUP_MD, toc: true },
  "anti-spam": { slug: "anti-spam", path: "/anti-spam", title: "Anti-Spam & Messaging Policy", short: "Anti-Spam", description: "Consent, compliance, and quality standards for sending messages.", markdown: ANTI_SPAM_MD, toc: true },
  "sms-terms": { slug: "sms-terms", path: "/sms-terms", title: "SMS / Messaging Terms & Consent", short: "SMS Terms", description: "How SMS works on Xellvio for end users and senders.", markdown: SMS_TERMS_MD, toc: false },
  dpa: { slug: "dpa", path: "/dpa", title: "Data Processing Addendum", short: "DPA", description: "Data-protection terms between Xellvio (processor) and Customers (controllers).", markdown: DPA_MD, toc: true },
  cookies: { slug: "cookies", path: "/cookies", title: "Cookie Policy", short: "Cookies", description: "How Xellvio uses cookies and similar technologies.", markdown: COOKIES_MD, toc: false },
};
