/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSetupSmsRouteImport } from './routes/api.setup-sms'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api.public.twilio-status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api.public.twilio-inbound'
import { Route as ApiPublicPollVerificationsRouteImport } from './routes/api.public.poll-verifications'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api.public.paystack-webhook'
import { Route as ApiPublicDispatchCampaignRouteImport } from './routes/api.public.dispatch-campaign'
import { Route as AuthenticatedAppSuppressionsRouteImport } from './routes/_authenticated.app.suppressions'
import { Route as AuthenticatedAppSetupSmsRouteImport } from './routes/_authenticated.app.setup-sms'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppSegmentsRouteImport } from './routes/_authenticated.app.segments'
import { Route as AuthenticatedAppPricingCalculatorRouteImport } from './routes/_authenticated.app.pricing-calculator'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated.app.onboarding'
import { Route as AuthenticatedAppNumberRequestsRouteImport } from './routes/_authenticated.app.number-requests'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated.app.campaigns'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated.app.billing'
import { Route as AuthenticatedAppAudienceRouteImport } from './routes/_authenticated.app.audience'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminRatesRouteImport } from './routes/_authenticated.admin.rates'
import { Route as AuthenticatedAdminNumberRequestsRouteImport } from './routes/_authenticated.admin.number-requests'
import { Route as AuthenticatedAdminMessagingRouteImport } from './routes/_authenticated.admin.messaging'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated.admin.messages'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated.admin.billing'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated.admin.activity'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated.admin.accounts'
import { Route as AuthenticatedAppSegmentsIndexRouteImport } from './routes/_authenticated.app.segments.index'
import { Route as AuthenticatedAppCampaignsIndexRouteImport } from './routes/_authenticated.app.campaigns.index'
import { Route as AuthenticatedAppSegmentsNewRouteImport } from './routes/_authenticated.app.segments.new'
import { Route as AuthenticatedAppCampaignsNewRouteImport } from './routes/_authenticated.app.campaigns.new'
import { Route as AuthenticatedAppCampaignsIdRouteImport } from './routes/_authenticated.app.campaigns.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupSmsRoute = ApiSetupSmsRouteImport.update({
  id: '/api/setup-sms',
  path: '/api/setup-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio-status',
  path: '/api/public/twilio-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio-inbound',
  path: '/api/public/twilio-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPollVerificationsRoute =
  ApiPublicPollVerificationsRouteImport.update({
    id: '/api/public/poll-verifications',
    path: '/api/public/poll-verifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDispatchCampaignRoute =
  ApiPublicDispatchCampaignRouteImport.update({
    id: '/api/public/dispatch-campaign',
    path: '/api/public/dispatch-campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSuppressionsRoute =
  AuthenticatedAppSuppressionsRouteImport.update({
    id: '/suppressions',
    path: '/suppressions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSetupSmsRoute =
  AuthenticatedAppSetupSmsRouteImport.update({
    id: '/setup-sms',
    path: '/setup-sms',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSegmentsRoute =
  AuthenticatedAppSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPricingCalculatorRoute =
  AuthenticatedAppPricingCalculatorRouteImport.update({
    id: '/pricing-calculator',
    path: '/pricing-calculator',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNumberRequestsRoute =
  AuthenticatedAppNumberRequestsRouteImport.update({
    id: '/number-requests',
    path: '/number-requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAudienceRoute =
  AuthenticatedAppAudienceRouteImport.update({
    id: '/audience',
    path: '/audience',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRatesRoute = AuthenticatedAdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNumberRequestsRoute =
  AuthenticatedAdminNumberRequestsRouteImport.update({
    id: '/number-requests',
    path: '/number-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagingRoute =
  AuthenticatedAdminMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppSegmentsIndexRoute =
  AuthenticatedAppSegmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSegmentsRoute,
  } as any)
const AuthenticatedAppCampaignsIndexRoute =
  AuthenticatedAppCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppSegmentsNewRoute =
  AuthenticatedAppSegmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppSegmentsRoute,
  } as any)
const AuthenticatedAppCampaignsNewRoute =
  AuthenticatedAppCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppCampaignsIdRoute =
  AuthenticatedAppCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/setup-sms': typeof ApiSetupSmsRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/number-requests': typeof AuthenticatedAdminNumberRequestsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/audience': typeof AuthenticatedAppAudienceRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/number-requests': typeof AuthenticatedAppNumberRequestsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pricing-calculator': typeof AuthenticatedAppPricingCalculatorRoute
  '/app/segments': typeof AuthenticatedAppSegmentsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup-sms': typeof AuthenticatedAppSetupSmsRoute
  '/app/suppressions': typeof AuthenticatedAppSuppressionsRoute
  '/api/public/dispatch-campaign': typeof ApiPublicDispatchCampaignRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/poll-verifications': typeof ApiPublicPollVerificationsRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/segments/new': typeof AuthenticatedAppSegmentsNewRoute
  '/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/segments/': typeof AuthenticatedAppSegmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/setup-sms': typeof ApiSetupSmsRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/number-requests': typeof AuthenticatedAdminNumberRequestsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/audience': typeof AuthenticatedAppAudienceRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/number-requests': typeof AuthenticatedAppNumberRequestsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pricing-calculator': typeof AuthenticatedAppPricingCalculatorRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/setup-sms': typeof AuthenticatedAppSetupSmsRoute
  '/app/suppressions': typeof AuthenticatedAppSuppressionsRoute
  '/api/public/dispatch-campaign': typeof ApiPublicDispatchCampaignRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/poll-verifications': typeof ApiPublicPollVerificationsRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/segments/new': typeof AuthenticatedAppSegmentsNewRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/segments': typeof AuthenticatedAppSegmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/setup-sms': typeof ApiSetupSmsRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/_authenticated/admin/number-requests': typeof AuthenticatedAdminNumberRequestsRoute
  '/_authenticated/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/audience': typeof AuthenticatedAppAudienceRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/_authenticated/app/number-requests': typeof AuthenticatedAppNumberRequestsRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/pricing-calculator': typeof AuthenticatedAppPricingCalculatorRoute
  '/_authenticated/app/segments': typeof AuthenticatedAppSegmentsRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/setup-sms': typeof AuthenticatedAppSetupSmsRoute
  '/_authenticated/app/suppressions': typeof AuthenticatedAppSuppressionsRoute
  '/api/public/dispatch-campaign': typeof ApiPublicDispatchCampaignRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/poll-verifications': typeof ApiPublicPollVerificationsRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/_authenticated/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/_authenticated/app/segments/new': typeof AuthenticatedAppSegmentsNewRoute
  '/_authenticated/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/_authenticated/app/segments/': typeof AuthenticatedAppSegmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/solutions'
    | '/verify-email'
    | '/admin'
    | '/app'
    | '/api/setup-sms'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/messages'
    | '/admin/messaging'
    | '/admin/number-requests'
    | '/admin/rates'
    | '/admin/users'
    | '/app/audience'
    | '/app/billing'
    | '/app/campaigns'
    | '/app/number-requests'
    | '/app/onboarding'
    | '/app/pricing-calculator'
    | '/app/segments'
    | '/app/settings'
    | '/app/setup-sms'
    | '/app/suppressions'
    | '/api/public/dispatch-campaign'
    | '/api/public/paystack-webhook'
    | '/api/public/poll-verifications'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/admin/'
    | '/app/'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/segments/new'
    | '/app/campaigns/'
    | '/app/segments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/solutions'
    | '/verify-email'
    | '/api/setup-sms'
    | '/admin/accounts'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/messages'
    | '/admin/messaging'
    | '/admin/number-requests'
    | '/admin/rates'
    | '/admin/users'
    | '/app/audience'
    | '/app/billing'
    | '/app/number-requests'
    | '/app/onboarding'
    | '/app/pricing-calculator'
    | '/app/settings'
    | '/app/setup-sms'
    | '/app/suppressions'
    | '/api/public/dispatch-campaign'
    | '/api/public/paystack-webhook'
    | '/api/public/poll-verifications'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/admin'
    | '/app'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/segments/new'
    | '/app/campaigns'
    | '/app/segments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/solutions'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/api/setup-sms'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/messaging'
    | '/_authenticated/admin/number-requests'
    | '/_authenticated/admin/rates'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/audience'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/number-requests'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/pricing-calculator'
    | '/_authenticated/app/segments'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/setup-sms'
    | '/_authenticated/app/suppressions'
    | '/api/public/dispatch-campaign'
    | '/api/public/paystack-webhook'
    | '/api/public/poll-verifications'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/campaigns/$id'
    | '/_authenticated/app/campaigns/new'
    | '/_authenticated/app/segments/new'
    | '/_authenticated/app/campaigns/'
    | '/_authenticated/app/segments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolutionsRoute: typeof SolutionsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSetupSmsRoute: typeof ApiSetupSmsRoute
  ApiPublicDispatchCampaignRoute: typeof ApiPublicDispatchCampaignRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicPollVerificationsRoute: typeof ApiPublicPollVerificationsRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-sms': {
      id: '/api/setup-sms'
      path: '/api/setup-sms'
      fullPath: '/api/setup-sms'
      preLoaderRoute: typeof ApiSetupSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/twilio-status': {
      id: '/api/public/twilio-status'
      path: '/api/public/twilio-status'
      fullPath: '/api/public/twilio-status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-inbound': {
      id: '/api/public/twilio-inbound'
      path: '/api/public/twilio-inbound'
      fullPath: '/api/public/twilio-inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll-verifications': {
      id: '/api/public/poll-verifications'
      path: '/api/public/poll-verifications'
      fullPath: '/api/public/poll-verifications'
      preLoaderRoute: typeof ApiPublicPollVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-campaign': {
      id: '/api/public/dispatch-campaign'
      path: '/api/public/dispatch-campaign'
      fullPath: '/api/public/dispatch-campaign'
      preLoaderRoute: typeof ApiPublicDispatchCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/suppressions': {
      id: '/_authenticated/app/suppressions'
      path: '/suppressions'
      fullPath: '/app/suppressions'
      preLoaderRoute: typeof AuthenticatedAppSuppressionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/setup-sms': {
      id: '/_authenticated/app/setup-sms'
      path: '/setup-sms'
      fullPath: '/app/setup-sms'
      preLoaderRoute: typeof AuthenticatedAppSetupSmsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/segments': {
      id: '/_authenticated/app/segments'
      path: '/segments'
      fullPath: '/app/segments'
      preLoaderRoute: typeof AuthenticatedAppSegmentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pricing-calculator': {
      id: '/_authenticated/app/pricing-calculator'
      path: '/pricing-calculator'
      fullPath: '/app/pricing-calculator'
      preLoaderRoute: typeof AuthenticatedAppPricingCalculatorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/number-requests': {
      id: '/_authenticated/app/number-requests'
      path: '/number-requests'
      fullPath: '/app/number-requests'
      preLoaderRoute: typeof AuthenticatedAppNumberRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audience': {
      id: '/_authenticated/app/audience'
      path: '/audience'
      fullPath: '/app/audience'
      preLoaderRoute: typeof AuthenticatedAppAudienceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rates': {
      id: '/_authenticated/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AuthenticatedAdminRatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/number-requests': {
      id: '/_authenticated/admin/number-requests'
      path: '/number-requests'
      fullPath: '/admin/number-requests'
      preLoaderRoute: typeof AuthenticatedAdminNumberRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messaging': {
      id: '/_authenticated/admin/messaging'
      path: '/messaging'
      fullPath: '/admin/messaging'
      preLoaderRoute: typeof AuthenticatedAdminMessagingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/segments/': {
      id: '/_authenticated/app/segments/'
      path: '/'
      fullPath: '/app/segments/'
      preLoaderRoute: typeof AuthenticatedAppSegmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSegmentsRoute
    }
    '/_authenticated/app/campaigns/': {
      id: '/_authenticated/app/campaigns/'
      path: '/'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/segments/new': {
      id: '/_authenticated/app/segments/new'
      path: '/new'
      fullPath: '/app/segments/new'
      preLoaderRoute: typeof AuthenticatedAppSegmentsNewRouteImport
      parentRoute: typeof AuthenticatedAppSegmentsRoute
    }
    '/_authenticated/app/campaigns/new': {
      id: '/_authenticated/app/campaigns/new'
      path: '/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAppCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/campaigns/$id': {
      id: '/_authenticated/app/campaigns/$id'
      path: '/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminMessagingRoute: typeof AuthenticatedAdminMessagingRoute
  AuthenticatedAdminNumberRequestsRoute: typeof AuthenticatedAdminNumberRequestsRoute
  AuthenticatedAdminRatesRoute: typeof AuthenticatedAdminRatesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminMessagingRoute: AuthenticatedAdminMessagingRoute,
  AuthenticatedAdminNumberRequestsRoute: AuthenticatedAdminNumberRequestsRoute,
  AuthenticatedAdminRatesRoute: AuthenticatedAdminRatesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppCampaignsRouteChildren {
  AuthenticatedAppCampaignsIdRoute: typeof AuthenticatedAppCampaignsIdRoute
  AuthenticatedAppCampaignsNewRoute: typeof AuthenticatedAppCampaignsNewRoute
  AuthenticatedAppCampaignsIndexRoute: typeof AuthenticatedAppCampaignsIndexRoute
}

const AuthenticatedAppCampaignsRouteChildren: AuthenticatedAppCampaignsRouteChildren =
  {
    AuthenticatedAppCampaignsIdRoute: AuthenticatedAppCampaignsIdRoute,
    AuthenticatedAppCampaignsNewRoute: AuthenticatedAppCampaignsNewRoute,
    AuthenticatedAppCampaignsIndexRoute: AuthenticatedAppCampaignsIndexRoute,
  }

const AuthenticatedAppCampaignsRouteWithChildren =
  AuthenticatedAppCampaignsRoute._addFileChildren(
    AuthenticatedAppCampaignsRouteChildren,
  )

interface AuthenticatedAppSegmentsRouteChildren {
  AuthenticatedAppSegmentsNewRoute: typeof AuthenticatedAppSegmentsNewRoute
  AuthenticatedAppSegmentsIndexRoute: typeof AuthenticatedAppSegmentsIndexRoute
}

const AuthenticatedAppSegmentsRouteChildren: AuthenticatedAppSegmentsRouteChildren =
  {
    AuthenticatedAppSegmentsNewRoute: AuthenticatedAppSegmentsNewRoute,
    AuthenticatedAppSegmentsIndexRoute: AuthenticatedAppSegmentsIndexRoute,
  }

const AuthenticatedAppSegmentsRouteWithChildren =
  AuthenticatedAppSegmentsRoute._addFileChildren(
    AuthenticatedAppSegmentsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAudienceRoute: typeof AuthenticatedAppAudienceRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRouteWithChildren
  AuthenticatedAppNumberRequestsRoute: typeof AuthenticatedAppNumberRequestsRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPricingCalculatorRoute: typeof AuthenticatedAppPricingCalculatorRoute
  AuthenticatedAppSegmentsRoute: typeof AuthenticatedAppSegmentsRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSetupSmsRoute: typeof AuthenticatedAppSetupSmsRoute
  AuthenticatedAppSuppressionsRoute: typeof AuthenticatedAppSuppressionsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAudienceRoute: AuthenticatedAppAudienceRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRouteWithChildren,
  AuthenticatedAppNumberRequestsRoute: AuthenticatedAppNumberRequestsRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPricingCalculatorRoute:
    AuthenticatedAppPricingCalculatorRoute,
  AuthenticatedAppSegmentsRoute: AuthenticatedAppSegmentsRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSetupSmsRoute: AuthenticatedAppSetupSmsRoute,
  AuthenticatedAppSuppressionsRoute: AuthenticatedAppSuppressionsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolutionsRoute: SolutionsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSetupSmsRoute: ApiSetupSmsRoute,
  ApiPublicDispatchCampaignRoute: ApiPublicDispatchCampaignRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicPollVerificationsRoute: ApiPublicPollVerificationsRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
